"""Node C -- Framework Supervisor.

Assembles the generation context (execution plan + retry diagnostics + golden
structural references from the AST knowledge base) and produces the monolith
``train_and_val.py``. The LLM sub-agent dispatch (PyTorch/TF/Keras) will be
injected later; for the structural compile this emits a deterministic,
contract-complete PyTorch template so the full self-healing graph can run.
"""
from __future__ import annotations

import logging
import os
import re
import sqlite3
from pathlib import Path

from .state import AgentState

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
AST_DB_PATH = REPO_ROOT / "data" / "ast_index.sqlite"
ENV_FILE_PATH = REPO_ROOT / ".env"
EXTRACTED_PAPERS_DIR = REPO_ROOT / "docs" / "extracted_papers"
FRAMEWORK_TEMPLATES_DIR = REPO_ROOT / "docs" / "framework_templates"
PINN_TRAINING_TEMPLATE_PATH = FRAMEWORK_TEMPLATES_DIR / "pytorch_pinn_training.md"
# Cap the paper text injected into the prompt (methodology-first papers fit well within this).
PAPER_TEXT_CHAR_LIMIT = 12000
LOGGER = logging.getLogger(__name__)
DEFAULT_GEMINI_MODELS = ("gemini-2.5-pro", "gemini-2.5-flash")
_SKIP_LLM_FOR_SESSION = False

try:
    from google import genai
except Exception:  # pragma: no cover - import availability is environment-specific
    genai = None


def _fetch_golden_references(
    limit: int = 4, execution_plan: str = ""
) -> list[tuple[str, str]]:
    """Pull up to ``limit`` (repo::qualname, source) golden symbols from the
    AST index as structural references, biased toward keywords found in the
    execution plan (RAG grounding). Returns [] if the index is absent so
    Node C degrades gracefully on a fresh checkout."""
    if not AST_DB_PATH.is_file():
        return []

    # Derive retrieval keywords from the execution plan; always include the
    # structural anchors (model/loss) so a sparse plan still grounds well.
    plan_lower = execution_plan.lower()
    keywords = ["model", "loss"]
    for kw in ("pinn", "cnn", "conv", "unet", "residual", "lstm", "physics",
               "boundary", "spectral", "navier", "incompressible"):
        if kw in plan_lower:
            keywords.append(kw)

    clause = " OR ".join("lower(qualname) LIKE ?" for _ in keywords)
    params = [f"%{kw}%" for kw in keywords]

    conn = sqlite3.connect(AST_DB_PATH)
    try:
        rows = conn.execute(
            "SELECT repo_name, qualname, source_code FROM symbol_chunks "
            f"WHERE {clause} "
            "ORDER BY repo_name, qualname LIMIT ?",
            (*params, limit),
        ).fetchall()
    finally:
        conn.close()
    return [(f"{repo}::{qual}", src) for repo, qual, src in rows]


def _load_paper_text(paper_id: str) -> str:
    """Load the extracted markdown of the target paper for traceability grounding.

    Returns '' when no extraction exists, so the prompt can honestly mark
    citations as UNAVAILABLE instead of fabricating section/page numbers.
    """
    if not paper_id:
        return ""
    candidate = EXTRACTED_PAPERS_DIR / paper_id / f"{paper_id}.md"
    if not candidate.is_file():
        return ""
    try:
        text = candidate.read_text(encoding="utf-8")
    except Exception as exc:
        LOGGER.warning("Node C: failed to read extracted paper %s (%s)", candidate, exc)
        return ""
    return text[:PAPER_TEXT_CHAR_LIMIT]


def _load_framework_template() -> str:
    """Load the PyTorch PINN training best-practices template for RAG injection."""
    if not PINN_TRAINING_TEMPLATE_PATH.is_file():
        LOGGER.warning(
            "Node C: framework template missing at %s; prompt will omit the framework reference",
            PINN_TRAINING_TEMPLATE_PATH,
        )
        return ""
    try:
        return PINN_TRAINING_TEMPLATE_PATH.read_text(encoding="utf-8")
    except Exception as exc:
        LOGGER.warning("Node C: failed to read framework template (%s)", exc)
        return ""


# Contract-complete PyTorch monolith (validated against the T0-T3 harness):
# per-pixel MLP, finite BC loss, short train loop.
_MONOLITH_TEMPLATE = '''\
"""Auto-generated by Node C (Framework Supervisor). Iteration: {iteration}.
{retry_note}
Structural references consulted: {references}
"""
import torch
import torch.nn as nn
import torch.nn.functional as F


class Model(nn.Module):
    """Per-pixel MLP (3 -> 64 -> 64 -> 3)."""

    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(3, 64), nn.Tanh(),
            nn.Linear(64, 64), nn.Tanh(),
            nn.Linear(64, 3),
        )

    def forward(self, x):
        b, c, h, w = x.shape
        y = self.net(x.permute(0, 2, 3, 1).reshape(-1, c))
        return y.reshape(b, h, w, c).permute(0, 3, 1, 2)

    def compute_bc_loss(self, batch):
        pred = self(batch.x)
        return F.mse_loss(pred, torch.zeros_like(pred))


def train_short_loop(seed=0):
    torch.manual_seed(seed)
    model = Model()
    opt = torch.optim.Adam(model.parameters(), lr=1e-2)
    x = torch.randn(2, 3, 4, 4)
    y = torch.randn(2, 3, 4, 4)
    loss = torch.tensor(float("inf"))
    for _ in range(300):
        opt.zero_grad()
        loss = F.mse_loss(model(x), y)
        loss.backward()
        opt.step()
    return {{"val_loss": loss.item()}}
'''


_PINN_FALLBACK_TEMPLATE = '''\
"""Auto-generated PINN fallback. Iteration: {iteration}.
{retry_note}
Structural references consulted: {references}
"""
import torch
import torch.nn as nn


class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(2, 64), nn.Tanh(),
            nn.Linear(64, 64), nn.Tanh(),
            nn.Linear(64, 3),
        )

    def forward(self, x, y):
        coords = torch.cat([x, y], dim=1)
        fields = self.net(coords)
        u = fields[:, 0:1]
        v = fields[:, 1:2]
        p = fields[:, 2:3]
        return u, v, p
'''


CNN_SYSTEM_PROMPT = (
    "You are the Framework Supervisor for a deterministic SciML-CFD pipeline.\n"
    "Generate ONLY a valid PyTorch train_and_val.py module for FIELD-BASED CNN/SURROGATE models.\n\n"
    "TRACEABILITY MATRIX (MANDATORY -- read first):\n"
    "- Your generated code string MUST BEGIN with a multi-line Python comment ('''...''') containing a\n"
    "  strict JSON object named the traceability matrix.\n"
    "- The JSON MUST map each of the following keys to an object with 'value', 'section', and 'page'\n"
    "  citing the EXACT section and page number of the provided paper text:\n"
    "    network_inputs, network_outputs, activation_functions, layer_depths,\n"
    "    pde_formulation, loss_function_components\n"
    "- network_outputs must list EVERY output variable the paper specifies (do not drop variables).\n"
    "- pde_formulation must state the exact residual equations used by the paper.\n"
    "- loss_function_components must distinguish supervised (boundary/data) vs unsupervised (residual) terms.\n"
    "- If the paper text is not provided below, write \"section\": \"UNAVAILABLE\" instead of inventing one.\n\n"
    "HARD CONTRACT (violations are auto-rejected by an immutable test harness):\n"
    "1) Output MUST be Python code only, in one ```python fenced block, no prose.\n"
    "2) The module MUST export exactly these symbols:\n"
    "   - class Model(torch.nn.Module) with forward(self, x)\n"
    "   - Model.compute_bc_loss(self, batch)  # batch has .x, .y, .variable_names\n"
    "   - def train_short_loop(seed=0) -> {\"val_loss\": float}\n"
    "3) Do NOT define get_dummy_batch(). The harness supplies its own evaluation batch:\n"
    "   x has shape (2, 3, 64, 64) float32/float64 on CPU; forward(x) must return the SAME shape.\n\n"
    "GRADIENT CONTINUITY (T1 gates):\n"
    "- All losses (including compute_bc_loss) MUST return differentiable scalar tensors.\n"
    "- NEVER call .detach(), .item(), .numpy(), or convert to Python floats inside any loss path.\n"
    "- Every trainable parameter must participate in forward() so gradients reach it.\n"
    "- No in-place ops on tensors that require grad; no torch.no_grad() inside loss computation.\n\n"
    "SPECTRAL SMOOTHNESS (T2 spectral-fidelity gate):\n"
    "- Use SMOOTH activations: SiLU, GELU, Tanh, or Sin (for PINNs). Avoid ReLU kinks in output layers.\n"
    "- HARD BAN: nn.ConvTranspose2d and nn.PixelShuffle are FORBIDDEN (checkerboard artifacts).\n"
    "- Standard upsampling pattern: nn.Upsample(mode='bilinear', align_corners=False) followed by nn.Conv2d.\n"
    "- Do NOT inject noise into outputs. Predicted fields must have physically plausible "
    "(decaying) high-frequency spectra -- prefer an explicit low-pass path (pooled bottleneck or 5x5+ kernels).\n\n"
    "CONTRACT COMPLIANCE:\n"
    "- Keep outputs in a standard scale (roughly unit-magnitude; no exp() blowups, no huge constants).\n"
    "- Use exact method signatures shown above; extra helpers are allowed, missing symbols are not.\n"
    "- CPU-only, minimal imports (torch, torch.nn, torch.nn.functional), deterministic seeds.\n"
    "- Honor every constraint in the execution plan (e.g. output floors) using smooth operations.\n\n"
)


PINN_SYSTEM_PROMPT = (
    "You are the Framework Supervisor for a deterministic SciML-CFD pipeline.\n"
    "Generate ONLY a valid PyTorch train_and_val.py module for a CONTINUOUS PHYSICS-INFORMED NEURAL NETWORK (PINN).\n\n"
    "TRACEABILITY MATRIX (MANDATORY -- read first):\n"
    "- Your generated code string MUST BEGIN with a multi-line Python comment ('''...''') containing a\n"
    "  strict JSON object named the traceability matrix.\n"
    "- The JSON MUST map each of the following keys to an object with 'value', 'section', and 'page'\n"
    "  citing the EXACT section and page number of the provided paper text:\n"
    "    network_inputs, network_outputs, activation_functions, layer_depths,\n"
    "    pde_formulation, loss_function_components\n"
    "- network_outputs must list EVERY output variable the paper specifies (e.g., if the paper outputs\n"
    "  6 variables such as U, V, P and Reynolds stresses uu, uv, vv -- list all 6).\n"
    "- pde_formulation must state the exact residual equations used by the paper.\n"
    "- loss_function_components must distinguish supervised (boundary/data) vs unsupervised (residual) terms.\n"
    "- If the paper text is not provided below, write \"section\": \"UNAVAILABLE\" instead of inventing one.\n\n"
    "PHYSICS-SPECIFIC EXTRACTION (MANDATORY):\n"
    "- Do not use generic Navier-Stokes templates. You must read the methodology section of the provided\n"
    "  text. If the paper specifies RANS, your neural network must output the exact Reynolds stress\n"
    "  components specified, and your PDE residual function must compute their gradients exactly as\n"
    "  formulated in the text.\n"
    "- Name the residual function `navier_stokes_residuals` and include every Reynolds-stress gradient\n"
    "  term the paper's momentum equations contain.\n\n"
    "HARD CONTRACT (violations are auto-rejected by the PINN harness):\n"
    "1) Output MUST be Python code only, in one ```python fenced block, no prose.\n"
    "2) The module MUST export exactly this symbol:\n"
    "   - class Model(torch.nn.Module) with forward(self, x, y)\n"
    "3) forward(self, x, y) MUST accept continuous spatial inputs x, y each shaped (B, 1), with requires_grad=True.\n"
    "4) forward(self, x, y) MUST return exactly three fields (u, v, p), each shaped (B, 1) -- the harness\n"
    "   unpacks exactly three values. If the paper specifies additional outputs (e.g., Reynolds stresses),\n"
    "   the network output layer MUST still predict them; expose the full set via a separate method\n"
    "   `forward_full(self, x, y)` returning ALL paper-specified fields, and use `forward_full` inside\n"
    "   `navier_stokes_residuals`.\n"
    "5) Use a DEEP MLP with Linear and Tanh activations. CNN layers are FORBIDDEN: no Conv1d/2d/3d, no pooling, no upsampling.\n"
    "6) Preserve autograd connectivity so torch.autograd.grad(outputs=u, inputs=x, ...) and dv/dy both work.\n"
    "7) NEVER use detach(), item(), numpy(), or non-differentiable conversions inside forward().\n"
    "8) Keep imports minimal and CPU-safe.\n"
    "9) The module MUST also define `train_model(...)` and `validate(...)` functions implementing the\n"
    "   FULL training/validation logic. Extract the specific optimizers the paper uses (e.g., Adam\n"
    "   followed by (L-)BFGS) and implement them using the exact syntax shown in the FRAMEWORK\n"
    "   REFERENCE section below -- including a proper `closure()` for L-BFGS.\n"
    "10) Keep default epoch/iteration counts small enough for a CPU smoke run (<= 200 Adam epochs,\n"
    "    <= 100 L-BFGS iterations) while preserving the paper's optimizer structure.\n\n"
)


def _fallback_monolith(failure_count: int, retry_note: str, reference_names: str) -> str:
    return _MONOLITH_TEMPLATE.format(
        iteration=failure_count + 1,
        retry_note=retry_note,
        references=reference_names,
    )


def _fallback_pinn_monolith(failure_count: int, retry_note: str, reference_names: str) -> str:
    return _PINN_FALLBACK_TEMPLATE.format(
        iteration=failure_count + 1,
        retry_note=retry_note,
        references=reference_names,
    )


def _resolve_model_names() -> tuple[str, ...]:
    """Resolve model names from env override or use safe defaults.

    `GEMINI_MODELS` supports a comma-separated list, e.g.:
    GEMINI_MODELS="gemini-2.5-pro,gemini-2.5-flash"
    """
    override = os.environ.get("GEMINI_MODELS", "").strip()
    if not override:
        return DEFAULT_GEMINI_MODELS
    models = tuple(m.strip() for m in override.split(",") if m.strip())
    return models or DEFAULT_GEMINI_MODELS


def _load_env_file_if_present() -> None:
    """Load simple KEY=VALUE pairs from repo-local .env into process env.

    Existing environment variables are not overwritten.
    """
    if not ENV_FILE_PATH.is_file():
        return

    try:
        for raw in ENV_FILE_PATH.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value
    except Exception as exc:
        LOGGER.warning("Node C: failed to read .env file at %s (%s)", ENV_FILE_PATH, exc)


def _is_not_found_or_deprecated(exc: Exception) -> bool:
    msg = str(exc).lower()
    return (
        "404" in msg
        or "not_found" in msg
        or "is not found" in msg
        or "no longeravailable" in msg
        or "no longer available" in msg
        or "deprecated" in msg
    )


def extract_python_code(raw_text: str) -> str:
    """Extract Python code from fenced blocks; fall back to raw output if absent."""
    if not raw_text:
        return ""

    matches = re.findall(r"```(?:python|py)?\s*(.*?)```", raw_text, flags=re.IGNORECASE | re.DOTALL)
    if not matches:
        LOGGER.warning("Node C LLM output had no fenced code block; using raw text fallback")
        return raw_text.strip()

    # Prefer the longest code block in case the model emits multiple snippets.
    return max(matches, key=len).strip()


# Targeted remediation guidance keyed off failure-fingerprint substrings.
_FINGERPRINT_REMEDIES: tuple[tuple[str, str], ...] = (
    ("t1:test_backward_finiteness",
     "Every parameter must receive a finite gradient from `output.sum().backward()`. "
     "Do not detach, clamp with non-differentiable ops, or route any branch around the graph."),
    ("t1:test_data_term_overfit_and_triviality",
     "The harness trains YOUR architecture with ITS OWN Adam(lr=1e-2) for exactly 50 steps -- "
     "your train_short_loop settings cannot help here. The architecture itself must converge fast: "
     "use a per-pixel MLP head (nn.Conv2d with kernel_size=1) as the primary mapping path, e.g. "
     "1x1 conv (3->128) -> GELU -> 1x1 conv (128->128) -> GELU -> 1x1 conv (128->3), optionally "
     "with ONE 3x3 conv branch added residually. MSE must drop 100x within 50 steps AND prediction "
     "std must stay above 10% of target std. Keep the output layer unconstrained (no final "
     "activation that limits range)."),
    ("t2:test_boundary_condition_loss_finiteness",
     "`compute_bc_loss(batch)` must return a FINITE differentiable scalar tensor for a "
     "(2, 3, 64, 64) input. Avoid division by tensors that can be zero and avoid log/sqrt of "
     "possibly-negative values."),
    ("t2:test_enforced_constraints",
     "Respect every declared blueprint constraint (e.g. output_floor: all outputs >= floor). "
     "Apply constraints smoothly (e.g. floor + softplus(x)) so gradients survive."),
    ("t2:test_mms_spectral_fidelity",
     "The output field's high-frequency PSD energy FRACTION (top 20% of wavenumbers along W) must "
     "match a decaying DNS turbulence spectrum within 15%. The evaluation input is mostly white "
     "noise, so the network MUST act as a low-pass filter. HARD BANS: never use nn.ConvTranspose2d "
     "(strided transposed convs cause checkerboard artifacts), never use nn.PixelShuffle, never add "
     "noise to outputs. REQUIRED: if you change resolution, upsample ONLY with "
     "nn.Upsample(mode='bilinear', align_corners=False) followed by a standard nn.Conv2d. To "
     "suppress high-frequency noise, include an explicit smoothing path: either an encoder-decoder "
     "bottleneck (AvgPool2d(2) -> convs -> bilinear Upsample) or 5x5+ convolution kernels. Use "
     "smooth activations (SiLU/GELU/Tanh) everywhere."),
    ("t3:test_short_train_regression_multi_seed",
     "`train_short_loop(seed)` must reach the blueprint's expected_validation_loss. Train on a "
     "learnable synthetic mapping (e.g. y = tanh(conv(x))) with enough steps (>= 200) and a "
     "stable lr (1e-2 Adam)."),
    ("SYNTAX",
     "The previous output was not importable Python. Emit ONLY plain Python source, no prose, "
     "no markdown outside a single fenced block."),
    ("HANG",
     "The previous run exceeded the time budget. Keep train_short_loop under ~300 quick CPU "
     "steps and never loop unboundedly at import time."),
)


def _remediation_for(fingerprint: str) -> str:
    """Assemble targeted fix instructions for every gate named in the fingerprint."""
    remedies = [advice for key, advice in _FINGERPRINT_REMEDIES if key in fingerprint]
    if not remedies:
        return "- Re-read the module contract and regenerate the full file from scratch.\n"
    return "".join(f"- {advice}\n" for advice in remedies)


def _build_prompt(
    execution_plan: str,
    failure_count: int,
    fingerprint: str,
    references: list[tuple[str, str]],
    architecture_mode: str,
    paper_text: str = "",
) -> str:
    retry_section = ""
    if failure_count > 0 and fingerprint:
        retry_section = (
            "RETRY CONTEXT (SELF-HEALING, attempt "
            f"{failure_count + 1}):\n"
            f"- error_fingerprint: {fingerprint}\n"
            "- TARGETED FIXES REQUIRED:\n"
            f"{_remediation_for(fingerprint)}"
            "- Regenerate the ENTIRE file with these fixes applied; do not repeat the failing pattern.\n\n"
        )

    if references:
        formatted_refs = []
        for name, src in references:
            snippet = src[:1200]
            formatted_refs.append(f"REFERENCE: {name}\n```python\n{snippet}\n```")
        refs_section = "\n\n".join(formatted_refs)
    else:
        refs_section = "(no AST references available)"

    system_prompt = PINN_SYSTEM_PROMPT if architecture_mode == "continuous_pinn" else CNN_SYSTEM_PROMPT

    framework_section = ""
    if architecture_mode == "continuous_pinn":
        framework_template = _load_framework_template()
        if framework_template:
            framework_section = (
                "FRAMEWORK REFERENCE (PyTorch Best Practices):\n"
                f"{framework_template}\n\n"
            )

    if paper_text:
        paper_section = f"PROVIDED PAPER TEXT (cite sections/pages from THIS text only):\n{paper_text}\n\n"
    else:
        paper_section = (
            "PROVIDED PAPER TEXT: none available -- mark all traceability sections as UNAVAILABLE.\n\n"
        )

    return (
        f"{system_prompt}"
        f"{framework_section}"
        f"{paper_section}"
        f"EXECUTION PLAN:\n{execution_plan}\n\n"
        f"{retry_section}"
        f"GOLDEN REFERENCE SNIPPETS (AST-indexed, structurally validated):\n{refs_section}\n"
    )


def _try_generate_with_gemini(prompt: str, model_names: tuple[str, ...] | None = None) -> str | None:
    """Attempt live Gemini generation; return None on any non-fatal failure."""
    global _SKIP_LLM_FOR_SESSION

    _load_env_file_if_present()

    if _SKIP_LLM_FOR_SESSION:
        LOGGER.warning(
            "Node C: skipping live Gemini calls for this process after repeated model availability failures"
        )
        return None

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        LOGGER.warning("Node C: GEMINI_API_KEY not found; using deterministic fallback template")
        return None
    if genai is None:
        LOGGER.warning("Node C: google-genai is unavailable; using deterministic fallback template")
        return None

    try:
        client = genai.Client(api_key=api_key)
    except Exception as exc:
        LOGGER.warning("Node C: failed to initialize Gemini client (%s); using fallback", exc)
        return None

    selected_models = model_names or _resolve_model_names()
    if not selected_models:
        selected_models = DEFAULT_GEMINI_MODELS

    all_failures_not_found_or_deprecated = True

    for model_name in selected_models:
        try:
            response = client.models.generate_content(model=model_name, contents=prompt)
            text = getattr(response, "text", None) or ""
            code = extract_python_code(text)
            if code:
                return code
            LOGGER.warning("Node C: empty generation from model '%s'; trying fallback model", model_name)
            all_failures_not_found_or_deprecated = False
        except Exception as exc:
            LOGGER.warning("Node C: generation failed for model '%s' (%s)", model_name, exc)
            all_failures_not_found_or_deprecated = (
                all_failures_not_found_or_deprecated and _is_not_found_or_deprecated(exc)
            )

    if all_failures_not_found_or_deprecated:
        _SKIP_LLM_FOR_SESSION = True
        LOGGER.warning(
            "Node C: all configured Gemini models appear unavailable/deprecated. "
            "Using deterministic fallback for the rest of this process. "
            "Set GEMINI_MODELS to current IDs (e.g. gemini-2.5-pro,gemini-2.5-flash)."
        )
    return None


def node_c_framework_supervisor(state: AgentState) -> dict:
    """Generate (or regenerate, on retry) the monolith from the execution plan."""
    execution_plan = state.get("execution_plan", "")
    architecture_mode = state.get("architecture_mode", "cnn_field")
    failure_count = state.get("failure_count", 0)
    fingerprint = state.get("error_fingerprint", "")

    references = _fetch_golden_references(limit=4, execution_plan=execution_plan)
    reference_names = ", ".join(name for name, _ in references) or "(AST index unavailable)"

    paper_text = _load_paper_text(str(state.get("paper_id", "")))
    if paper_text:
        LOGGER.info("Node C: grounding prompt with extracted paper text (%s chars)", len(paper_text))
    else:
        LOGGER.warning(
            "Node C: no extracted paper text found for paper_id=%s; traceability sections will be UNAVAILABLE",
            state.get("paper_id", ""),
        )

    if failure_count > 0 and fingerprint:
        retry_note = (
            f"RETRY CONTEXT: previous attempt failed with fingerprint '{fingerprint}'. "
            "The code below has been regenerated to address it."
        )
    else:
        retry_note = "First-pass generation from the execution plan."

    prompt = _build_prompt(
        execution_plan=execution_plan,
        failure_count=failure_count,
        fingerprint=fingerprint,
        references=references,
        architecture_mode=architecture_mode,
        paper_text=paper_text,
    )

    code = _try_generate_with_gemini(prompt)
    if code:
        LOGGER.info(
            "Node C: live LLM generation succeeded (attempt %s, %s chars, %s refs)",
            failure_count + 1, len(code), len(references),
        )
    else:
        LOGGER.warning(
            "Node C: using deterministic fallback template (attempt %s, fingerprint=%s)",
            failure_count + 1, fingerprint or "None",
        )
        if architecture_mode == "continuous_pinn":
            code = _fallback_pinn_monolith(
                failure_count=failure_count,
                retry_note=retry_note,
                reference_names=reference_names,
            )
        else:
            code = _fallback_monolith(
                failure_count=failure_count,
                retry_note=retry_note,
                reference_names=reference_names,
            )
    return {"generated_code": code}
