"""Node C -- Framework Supervisor.

Assembles the generation context (execution plan + retry diagnostics + golden
structural references from the AST knowledge base) and produces the monolith
``train_and_val.py``. The LLM sub-agent dispatch (PyTorch/TF/Keras) will be
injected later; for the structural compile this emits a deterministic,
contract-complete PyTorch template so the full self-healing graph can run.
"""
from __future__ import annotations

import logging
import os
import re
import sqlite3
from pathlib import Path

from .state import AgentState

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
AST_DB_PATH = REPO_ROOT / "data" / "ast_index.sqlite"
ENV_FILE_PATH = REPO_ROOT / ".env"
LOGGER = logging.getLogger(__name__)
DEFAULT_GEMINI_MODELS = ("gemini-2.5-pro", "gemini-2.5-flash")
_SKIP_LLM_FOR_SESSION = False

try:
    from google import genai
except Exception:  # pragma: no cover - import availability is environment-specific
    genai = None


def _fetch_golden_references(
    limit: int = 4, execution_plan: str = ""
) -> list[tuple[str, str]]:
    """Pull up to ``limit`` (repo::qualname, source) golden symbols from the
    AST index as structural references, biased toward keywords found in the
    execution plan (RAG grounding). Returns [] if the index is absent so
    Node C degrades gracefully on a fresh checkout."""
    if not AST_DB_PATH.is_file():
        return []

    # Derive retrieval keywords from the execution plan; always include the
    # structural anchors (model/loss) so a sparse plan still grounds well.
    plan_lower = execution_plan.lower()
    keywords = ["model", "loss"]
    for kw in ("pinn", "cnn", "conv", "unet", "residual", "lstm", "physics",
               "boundary", "spectral", "navier", "incompressible"):
        if kw in plan_lower:
            keywords.append(kw)

    clause = " OR ".join("lower(qualname) LIKE ?" for _ in keywords)
    params = [f"%{kw}%" for kw in keywords]

    conn = sqlite3.connect(AST_DB_PATH)
    try:
        rows = conn.execute(
            "SELECT repo_name, qualname, source_code FROM symbol_chunks "
            f"WHERE {clause} "
            "ORDER BY repo_name, qualname LIMIT ?",
            (*params, limit),
        ).fetchall()
    finally:
        conn.close()
    return [(f"{repo}::{qual}", src) for repo, qual, src in rows]


# Contract-complete PyTorch monolith (validated against the T0-T3 harness):
# per-pixel MLP, finite BC loss, short train loop.
_MONOLITH_TEMPLATE = '''\
"""Auto-generated by Node C (Framework Supervisor). Iteration: {iteration}.
{retry_note}
Structural references consulted: {references}
"""
import torch
import torch.nn as nn
import torch.nn.functional as F


class Model(nn.Module):
    """Per-pixel MLP (3 -> 64 -> 64 -> 3)."""

    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(3, 64), nn.Tanh(),
            nn.Linear(64, 64), nn.Tanh(),
            nn.Linear(64, 3),
        )

    def forward(self, x):
        b, c, h, w = x.shape
        y = self.net(x.permute(0, 2, 3, 1).reshape(-1, c))
        return y.reshape(b, h, w, c).permute(0, 3, 1, 2)

    def compute_bc_loss(self, batch):
        pred = self(batch.x)
        return F.mse_loss(pred, torch.zeros_like(pred))


def train_short_loop(seed=0):
    torch.manual_seed(seed)
    model = Model()
    opt = torch.optim.Adam(model.parameters(), lr=1e-2)
    x = torch.randn(2, 3, 4, 4)
    y = torch.randn(2, 3, 4, 4)
    loss = torch.tensor(float("inf"))
    for _ in range(300):
        opt.zero_grad()
        loss = F.mse_loss(model(x), y)
        loss.backward()
        opt.step()
    return {{"val_loss": loss.item()}}
'''


def _fallback_monolith(failure_count: int, retry_note: str, reference_names: str) -> str:
    return _MONOLITH_TEMPLATE.format(
        iteration=failure_count + 1,
        retry_note=retry_note,
        references=reference_names,
    )


def _resolve_model_names() -> tuple[str, ...]:
    """Resolve model names from env override or use safe defaults.

    `GEMINI_MODELS` supports a comma-separated list, e.g.:
    GEMINI_MODELS="gemini-2.5-pro,gemini-2.5-flash"
    """
    override = os.environ.get("GEMINI_MODELS", "").strip()
    if not override:
        return DEFAULT_GEMINI_MODELS
    models = tuple(m.strip() for m in override.split(",") if m.strip())
    return models or DEFAULT_GEMINI_MODELS


def _load_env_file_if_present() -> None:
    """Load simple KEY=VALUE pairs from repo-local .env into process env.

    Existing environment variables are not overwritten.
    """
    if not ENV_FILE_PATH.is_file():
        return

    try:
        for raw in ENV_FILE_PATH.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value
    except Exception as exc:
        LOGGER.warning("Node C: failed to read .env file at %s (%s)", ENV_FILE_PATH, exc)


def _is_not_found_or_deprecated(exc: Exception) -> bool:
    msg = str(exc).lower()
    return (
        "404" in msg
        or "not_found" in msg
        or "is not found" in msg
        or "no longeravailable" in msg
        or "no longer available" in msg
        or "deprecated" in msg
    )


def extract_python_code(raw_text: str) -> str:
    """Extract Python code from fenced blocks; fall back to raw output if absent."""
    if not raw_text:
        return ""

    matches = re.findall(r"```(?:python|py)?\s*(.*?)```", raw_text, flags=re.IGNORECASE | re.DOTALL)
    if not matches:
        LOGGER.warning("Node C LLM output had no fenced code block; using raw text fallback")
        return raw_text.strip()

    # Prefer the longest code block in case the model emits multiple snippets.
    return max(matches, key=len).strip()


# Targeted remediation guidance keyed off failure-fingerprint substrings.
_FINGERPRINT_REMEDIES: tuple[tuple[str, str], ...] = (
    ("t1:test_backward_finiteness",
     "Every parameter must receive a finite gradient from `output.sum().backward()`. "
     "Do not detach, clamp with non-differentiable ops, or route any branch around the graph."),
    ("t1:test_data_term_overfit_and_triviality",
     "The model must be able to overfit a single (B=2, C=3, H=64, W=64) batch: MSE loss must "
     "drop 100x within 50 Adam(lr=1e-2) steps AND prediction std must stay above 10% of target "
        "std. Increase the optimizer learning rate (e.g., AdamW with lr=5e-3) and ensure the network "
        "has sufficient capacity (e.g., a per-pixel MLP head) to drop the loss by two orders of "
        "magnitude within 50 steps. Keep an unconstrained output layer (no final activation that "
        "limits range)."),
    ("t2:test_boundary_condition_loss_finiteness",
     "`compute_bc_loss(batch)` must return a FINITE differentiable scalar tensor for a "
     "(2, 3, 64, 64) input. Avoid division by tensors that can be zero and avoid log/sqrt of "
     "possibly-negative values."),
    ("t2:test_enforced_constraints",
     "Respect every declared blueprint constraint (e.g. output_floor: all outputs >= floor). "
     "Apply constraints smoothly (e.g. floor + softplus(x)) so gradients survive."),
    ("t2:test_mms_spectral_fidelity",
     "The output field's high-frequency PSD energy (top 20% of wavenumbers along W) must stay "
     "within 15% of a reference turbulence spectrum. Use SMOOTH layers (conv with kernel >= 3 "
     "or per-pixel MLP with SiLU/GELU/Tanh), never checkerboard-prone ops (ConvTranspose with "
     "stride, PixelShuffle) and never add noise to outputs."),
    ("t3:test_short_train_regression_multi_seed",
     "`train_short_loop(seed)` must reach the blueprint's expected_validation_loss. Train on a "
     "learnable synthetic mapping (e.g. y = tanh(conv(x))) with enough steps (>= 200) and a "
     "stable lr (1e-2 Adam)."),
    ("SYNTAX",
     "The previous output was not importable Python. Emit ONLY plain Python source, no prose, "
     "no markdown outside a single fenced block."),
    ("HANG",
     "The previous run exceeded the time budget. Keep train_short_loop under ~300 quick CPU "
     "steps and never loop unboundedly at import time."),
)


def _remediation_for(fingerprint: str) -> str:
    """Assemble targeted fix instructions for every gate named in the fingerprint."""
    remedies = [advice for key, advice in _FINGERPRINT_REMEDIES if key in fingerprint]
    if not remedies:
        return "- Re-read the module contract and regenerate the full file from scratch.\n"
    return "".join(f"- {advice}\n" for advice in remedies)


def _build_prompt(
    execution_plan: str,
    failure_count: int,
    fingerprint: str,
    references: list[tuple[str, str]],
) -> str:
    retry_section = ""
    if failure_count > 0 and fingerprint:
        retry_section = (
            "RETRY CONTEXT (SELF-HEALING, attempt "
            f"{failure_count + 1}):\n"
            f"- error_fingerprint: {fingerprint}\n"
            "- TARGETED FIXES REQUIRED:\n"
            f"{_remediation_for(fingerprint)}"
            "- Regenerate the ENTIRE file with these fixes applied; do not repeat the failing pattern.\n\n"
        )

    if references:
        formatted_refs = []
        for name, src in references:
            snippet = src[:1200]
            formatted_refs.append(f"REFERENCE: {name}\n```python\n{snippet}\n```")
        refs_section = "\n\n".join(formatted_refs)
    else:
        refs_section = "(no AST references available)"

    return (
        "You are the Framework Supervisor for a deterministic SciML-CFD pipeline.\n"
        "Generate ONLY a valid PyTorch train_and_val.py module.\n\n"
        "HARD CONTRACT (violations are auto-rejected by an immutable test harness):\n"
        "1) Output MUST be Python code only, in one ```python fenced block, no prose.\n"
        "2) The module MUST export exactly these symbols:\n"
        "   - class Model(torch.nn.Module) with forward(self, x)\n"
        "   - Model.compute_bc_loss(self, batch)  # batch has .x, .y, .variable_names\n"
        "   - def train_short_loop(seed=0) -> {\"val_loss\": float}\n"
        "3) Do NOT define get_dummy_batch(). The harness supplies its own evaluation batch:\n"
        "   x has shape (2, 3, 64, 64) float32/float64 on CPU; forward(x) must return the SAME shape.\n\n"
        "GRADIENT CONTINUITY (T1 gates):\n"
        "- All losses (including compute_bc_loss) MUST return differentiable scalar tensors.\n"
        "- NEVER call .detach(), .item(), .numpy(), or convert to Python floats inside any loss path.\n"
        "- Every trainable parameter must participate in forward() so gradients reach it.\n"
        "- No in-place ops on tensors that require grad; no torch.no_grad() inside loss computation.\n\n"
        "SPECTRAL SMOOTHNESS (T2 spectral-fidelity gate):\n"
        "- Use SMOOTH activations: SiLU, GELU, Tanh, or Sin (for PINNs). Avoid ReLU kinks in output layers.\n"
        "- Do NOT inject noise, checkerboard patterns, PixelShuffle, or strided ConvTranspose upsampling.\n"
        "- Predicted fields must have physically plausible (decaying) high-frequency spectra.\n\n"
        "CONTRACT COMPLIANCE:\n"
        "- Keep outputs in a standard scale (roughly unit-magnitude; no exp() blowups, no huge constants).\n"
        "- Use exact method signatures shown above; extra helpers are allowed, missing symbols are not.\n"
        "- CPU-only, minimal imports (torch, torch.nn, torch.nn.functional), deterministic seeds.\n"
        "- Honor every constraint in the execution plan (e.g. output floors) using smooth operations.\n\n"
        f"EXECUTION PLAN:\n{execution_plan}\n\n"
        f"{retry_section}"
        f"GOLDEN REFERENCE SNIPPETS (AST-indexed, structurally validated):\n{refs_section}\n"
    )


def _try_generate_with_gemini(prompt: str, model_names: tuple[str, ...] | None = None) -> str | None:
    """Attempt live Gemini generation; return None on any non-fatal failure."""
    global _SKIP_LLM_FOR_SESSION

    _load_env_file_if_present()

    if _SKIP_LLM_FOR_SESSION:
        LOGGER.warning(
            "Node C: skipping live Gemini calls for this process after repeated model availability failures"
        )
        return None

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        LOGGER.warning("Node C: GEMINI_API_KEY not found; using deterministic fallback template")
        return None
    if genai is None:
        LOGGER.warning("Node C: google-genai is unavailable; using deterministic fallback template")
        return None

    try:
        client = genai.Client(api_key=api_key)
    except Exception as exc:
        LOGGER.warning("Node C: failed to initialize Gemini client (%s); using fallback", exc)
        return None

    selected_models = model_names or _resolve_model_names()
    if not selected_models:
        selected_models = DEFAULT_GEMINI_MODELS

    all_failures_not_found_or_deprecated = True

    for model_name in selected_models:
        try:
            response = client.models.generate_content(model=model_name, contents=prompt)
            text = getattr(response, "text", None) or ""
            code = extract_python_code(text)
            if code:
                return code
            LOGGER.warning("Node C: empty generation from model '%s'; trying fallback model", model_name)
            all_failures_not_found_or_deprecated = False
        except Exception as exc:
            LOGGER.warning("Node C: generation failed for model '%s' (%s)", model_name, exc)
            all_failures_not_found_or_deprecated = (
                all_failures_not_found_or_deprecated and _is_not_found_or_deprecated(exc)
            )

    if all_failures_not_found_or_deprecated:
        _SKIP_LLM_FOR_SESSION = True
        LOGGER.warning(
            "Node C: all configured Gemini models appear unavailable/deprecated. "
            "Using deterministic fallback for the rest of this process. "
            "Set GEMINI_MODELS to current IDs (e.g. gemini-2.5-pro,gemini-2.5-flash)."
        )
    return None


def node_c_framework_supervisor(state: AgentState) -> dict:
    """Generate (or regenerate, on retry) the monolith from the execution plan."""
    execution_plan = state.get("execution_plan", "")
    failure_count = state.get("failure_count", 0)
    fingerprint = state.get("error_fingerprint", "")

    references = _fetch_golden_references(limit=4, execution_plan=execution_plan)
    reference_names = ", ".join(name for name, _ in references) or "(AST index unavailable)"

    if failure_count > 0 and fingerprint:
        retry_note = (
            f"RETRY CONTEXT: previous attempt failed with fingerprint '{fingerprint}'. "
            "The code below has been regenerated to address it."
        )
    else:
        retry_note = "First-pass generation from the execution plan."

    prompt = _build_prompt(
        execution_plan=execution_plan,
        failure_count=failure_count,
        fingerprint=fingerprint,
        references=references,
    )

    code = _try_generate_with_gemini(prompt)
    if not code:
        code = _fallback_monolith(
            failure_count=failure_count,
            retry_note=retry_note,
            reference_names=reference_names,
        )
    return {"generated_code": code}
